# Generated by Django 4.0.5 on 2022-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_rename_text_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='social_link',
            field=models.URLField(blank=True),
        ),
    ]
